spring:
  application:
    name: CRM
    frontUrl: ${FRONT_URL:http://localhost:5173}
  profiles:
    default: dev
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}
  jpa:
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

server:
  port: ${PORT:8080}