spring:
  application:
    frontUrl: ${FRONT_URL}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

aws:
  s3:
    bucket: ${AWS_BUCKET:learning-center-uploads}
    region: ${AWS_REGION:eu-north-1}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

jwt:
  access:
    token:
      secretKey: ${JWT_ACCESS_SECRET_KEY}
      expire:
        date: ${JWT_ACCESS_EXPIRE_DATE:900}
  refresh:
    token:
      secretKey: ${JWT_REFRESH_SECRET_KEY}
      expire:
        date: ${JWT_REFRESH_EXPIRE_DATE:604800}

server:
  port: ${PORT:8080}